### ISSUE TITLE
[v1.0.0-beta2] Compile time issues in Xcode using 'AzureCommunicationUI'

### ISSUE THREAD

**Issue by JoshuaLai** [Azure/communication-ui-library-ios#134]
**Describe the bug**
Xcode is showing multiple compile time errors in the library 'AzureCommunicationUI', '1.0.0-beta.2'.

![Screenshot 2022-04-20 at 4 05 25 PM](https://user-images.githubusercontent.com/95396105/164213769-6270a217-69df-4e0d-b2eb-fd156109d835.png)

I am using Xcode 12.3 and swift language version 5

**To Reproduce**
1. Check out pod version in described Xcode version
2. This bug is always reproducible.

**Expected behavior**
Should not get build issues

**Screenshots**
![Screenshot 2022-04-20 at 4 05 25 PM](https://user-images.githubusercontent.com/95396105/164213769-6270a217-69df-4e0d-b2eb-fd156109d835.png)

**AzureCommunicationUILibrary (please complete the following information):**
 - Version v1.0.0-beta2

**Comment by JoshuaLai** [comment]
Migrating the git issue to the iOS repo [Kamaljeetsinghpunia](https://github.com/Kamaljeetsinghpunia)

**Comment by AmyL219** [comment]
[Kamaljeetsinghpunia](https://github.com/Kamaljeetsinghpunia), Thanks for reporting. Looks like the error is because you have a lower version of Xcode. 
Could you update your Xcode to latest version `13.3` and try to clean(`Shift`+`command`+`K`)/build the project again?

**Comment by AmyL219** [comment]
Close this issue as resolved since no response from [Kamaljeetsinghpunia](https://github.com/Kamaljeetsinghpunia) for more than 1 week
