### ISSUE TITLE
[v1.0.0] Crash at launching app with iOS 12/13

### ISSUE THREAD

**Issue by AlessandroFrangiamoneIriscube** [Azure/communication-ui-library-ios#475]
### **Description:**
We want to use your library having an application with min target iOS 12. We therefore used the documentation (FAQ) for installation on devices with iOS < 14.

After launching the app on the simulator with iOS 13 we encountered a crash of the app during startup. The issue also occurs on physical device.

### **Library version:** 
1.0.0

### **Device:**
Physical -> iPhone 5s (iOS 13.7)
Simulatore -> iPhone 11 Pro Max (iOS 13.7)

### **Error log:**
`dyld: Symbol not found: _$s7SwiftUI11StateObjectVMn

  Referenced from: /Users/andreamannucci/Library/Developer/CoreSimulator/Devices/5CD4583A-AA18-4AA8-9DB6-50DE6E7D3962/data/Containers/Bundle/Application/F0E8B235-CD51-4804-81A3-7EDFFCD54DB8/<app>/Frameworks/AzureCommunicationUICalling.framework/AzureCommunicationUICalling (which was built for iOS 14.0)

  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.7.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SwiftUI.framework/SwiftUI

in /Users/andreamannucci/Library/Developer/CoreSimulator/Devices/5CD4583A-AA18-4AA8-9DB6-50DE6E7D3962/data/Containers/Bundle/Application/F0E8B235-CD51-4804-81A3-7EDFFCD54DB8/<app>/Frameworks/AzureCommunicationUICalling.framework/AzureCommunicationUICalling

dyld: launch, loading dependent libraries

DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.7.simruntime/Contents/Resources/RuntimeRoot

DYLD_LIBRARY_PATH=/Users/andreamannucci/Library/Developer/Xcode/DerivedData/<>-bxzzbvcmrzierrbiivskzsorxcak/Build/Products/Debug-iphonesimulator:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.7.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection

DYLD_PRINT_STATISTICS=YES

DYLD_INSERT_LIBRARIES=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.7.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.7.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.7.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMTLCapture.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.7.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/Private`

Could you provide us with support?

Best regard,
Alessandro

**Comment by emlynmac** [comment]
Hi @AlessandroFrangiamoneIriscube,

Thanks for your feedback.
Can you provide your code sample project showing how you are instantiating the library so we can support you further?

**Comment by AlessandroFrangiamoneIriscube** [comment]
Hi @emlynmac,

The crash happens even without using the library.
The mere fact of having created the framework and integrated it into the project of our App, according to your documentation, causes the app to crash on startup, even if we don't use the framework.

**Comment by emlynmac** [comment]
Please provide a sample project showing the issue so I can assist you further.

**Comment by AlessandroFrangiamoneIriscube** [comment]
Hi @emlynmac , 
below is the link to the Github repository where you can find the sample project:
https://github.com/andremannu/AzureUI-Sample

To test the project, simply go to the root directory and run the "pod install" command. Before you also need to remove the first line of the Podfile: plugin 'cocoapods-art', :sources => ['cocoapods-local']. We use it because we have an artifactory repository.
The framework that includes the "AzureCommunicationUICalling" library is "AzureUIWrapper".

There will be a crash when starting the App, even on iOS 14 and above. In particular it seems that the linker can't find the AzureCommunicationCalling library at runtime. In addition to this we do not know how to solve the crash related to iOS 12 and 13 that we have written to you in recent days.
We ask for your support if possible for both crashes. Thank you.



Best Regards,
Alessandro


**Crash log:**
dyld[47737]: Library not loaded: @rpath/AzureCommunicationCalling.framework/AzureCommunicationCalling

  Referenced from: <17112C84-02D5-3A52-9F08-70401323B108> /Users/andreamannucci/Library/Developer/Xcode/DerivedData/AzureUI_Sample-fnbckzfurahgdaciutwmgkqezvdj/Build/Products/Debug-iphonesimulator/AzureUIWrapper.framework/AzureUIWrapper

  Reason: tried: '/Users/andreamannucci/Library/Developer/Xcode/DerivedData/AzureUI_Sample-fnbckzfurahgdaciutwmgkqezvdj/Build/Products/Debug-iphonesimulator/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2, no dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2, no dyld cache), '/Users/andreamannucci/Library/Developer/CoreSimulator/Devices/C8B86C04-D026-409E-974B-7499267F55EB/data/Containers/Bundle/Application/F68B04DF-7EDA-4418-8A41-0F0F6ED76A66/AzureUI Sample.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Users/andreamannucci/Library/Developer/Xcode/DerivedData/AzureUI_Sample-fnbckzfurahgdaciutwmgkqezvdj/Build/Products/Debug-iphonesimulator/AzureUIWrapper.framework/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Users/andreamannucci/Library/Developer/CoreSimulator/Devices/C8B86C04-D026-409E-974B-7499267F55EB/data/Containers/Bundle/Application/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Users/andreamannucci/Library/Developer/CoreSimulator/Devices/C8B86C04-D026-409E-974B-7499267F55EB/data/Containers/Bundle/Application/F68B04DF-7EDA-4418-8A41-0F0F6ED76A66/AzureUI Sample.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Users/andreamannucci/Library/Developer/Xcode/DerivedData/AzureUI_Sample-fnbckzfurahgdaciutwmgkqezvdj/Build/Products/Debug-iphonesimulator/AzureUIWrapper.framework/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2, no dyld cache), '/Users/andreamannucci/Library/Developer/CoreSimulator/Devices/C8B86C04-D026-409E-974B-7499267F55EB/data/Containers/Bundle/Application/F68B04DF-7EDA-4418-8A41-0F0F6ED76A66/AzureUI Sample.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2, no dyld cache), '/Users/andreamannucci/Library/Developer/CoreSimulator/Devices/C8B86C04-D026-409E-974B-7499267F55EB/data/Containers/Bundle/Application/F68B04DF-7EDA-4418-8A41-0F0F6ED76A66/AzureUI Sample.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2)

Library not loaded: @rpath/AzureCommunicationCalling.framework/AzureCommunicationCalling

  Referenced from: <17112C84-02D5-3A52-9F08-70401323B108> /Users/andreamannucci/Library/Developer/Xcode/DerivedData/AzureUI_Sample-fnbckzfurahgdaciutwmgkqezvdj/Build/Products/Debug-iphonesimulator/AzureUIWrapper.framework/AzureUIWrapper

  Reason: tried: '/Users/andreamannucci/Library/Developer/Xcode/DerivedData/AzureUI_Sample-fnbckzfurahgdaciutwmgkqezvdj/Build/Products/Debug-iphonesimulator/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2), '/usr/lib/swift/AzureCommunicationCalling.framework/AzureCommunicationCalling' (errno=2, no dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/P

dyld config: DYLD_SHARED_CACHE_DIR=/Users/andreamannucci/Library/Developer/CoreSimulator/Caches/dyld/21G115/com.apple.CoreSimulator.SimRuntime.iOS-16-1.20B72 DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/andreamannucci/Library/Developer/Xcode/DerivedData/AzureUI_Sample-fnbckzfurahgdaciutwmgkqezvdj/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/usr/lib/libRPAC.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/andreamannucci/Library/Developer/Xcode/DerivedData/AzureUI_Sample-fnbckzfurahgdaciutwmgkqezvdj/Build/Products/Debug-iphonesimulator DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks DYLD_FALLBACK_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib
(lldb)

**Comment by emlynmac** [comment]
Thanks for providing the sample.

The first issue is that the main app cannot link directly to the wrapper library - the wrapper framework is embedded in the binary but not linked. The library can only be loaded at run-time if the iOS version is sufficient. 

Secondarily, it looks like the cocoa pods dependency resolution does not work, so I've gone through the full manual install method. With this, the wrapper library is correctly embedding the necessary libraries.

The last hurdle I had was with the Bundle().principleClass.init() method not working. I've changed that to load the bundle by path in my fork and it does work.

Please have a look at the updated sample here:
https://github.com/emlynmac/AzureUI-Sample/tree/use-manual-install

I'll update our documentation on this - thanks for reporting the issue!

**Comment by emlynmac** [comment]
Documentation updated, closing this ticket.
