### ISSUE TITLE
Add Call Over to startCallComposite

### ISSUE THREAD

**Issue by cheymonty** [Azure/communication-ui-library-ios#611]
**What feature are you requesting?**
After creating the composite, there should be a way to know when the composite is closed (due to the meeting ending for all or the user leaving themselves)

**What would be the benefit of adding this feature?**
The app will be able to know when the call is over

**What solution would be ideal for you?**
a callback parameter or return value

**What alternatives have you considered?**
There are no alternatives

**Comment by Mohtasim** [comment]
Hi @cheymonty,
Thanks for your feature request. Currently our composite does not have the capability of what you are asking. We'll put your request in our backlog for further review and prioritization. 
But if it is an urgent requirement for your business need, our library is open source and you are most welcome to contribute around your feature request with a pull request. We'll review your contribution and help you through the process to get you the UI Library build.
Please follow our [contribution guideline](https://github.com/Azure/communication-ui-library-ios/blob/main/docs/contributing-guide.md) if you wanted to contribute around the feature.

**Comment by Mohtasim** [comment]
Re-opened the issue to track the feature request and provide update about our progress and release. 
Thank you.

**Comment by pavelprystinka** [comment]
Hi @cheymonty 

This feature was added in the 1.4.0 version. Please see this [tutorial](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=kotlin&pivots=platform-ios#dismiss-callcomposite-and-subscribe-to-dismissed-event).
