### ISSUE TITLE
[Calling SDK] No support for ARM64 simulator

### ISSUE THREAD

**Issue by emlynmac** [Azure/communication-ui-library-ios#640]
**Describe the bug**
Support for the Apple Silicon simulator is not included in the calling library.

A workaround has been used until Xcode 14.3; run Xcode in rosetta mode. This support has now been removed in Xcode > 14.3

This is a downstream tracking bug from https://github.com/Azure/azure-sdk-for-ios/issues/1497

**To Reproduce**
Attempt to use an apple silicon mac to build for simulator with the library

**Expected behaviour**
Build works on apple silicon simulator targets

**Comment by ShaunaSong** [comment]
Will wait for next xcode release.  https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes#Deprecations

**Comment by ahammer** [comment]
With 1.4.0 release of Calling UI, ARM64 Simulator support has been added.
