### ISSUE TITLE
Callkit Support for Communication ui library

### ISSUE THREAD

**Issue by kungbernard** [Azure/communication-ui-library-ios#653]
**What feature are you requesting?**
Allowing the Communication Ui library to support callkit integration for answering and hanging up incoming call. This feature is currently in beta under ACS iOS SDK 2.3.0 beta 1. https://github.com/Azure/Communication/releases
Would be great if the Ui library will also include this feature.

**What would be the benefit of adding this feature?**
Instead of needing the user to manually click the join call button, CallKit will allow user to answer the call even outside the app. Besides, the native UI callkit screen is the common user experience for iOS user using VoIP type app, including Microsoft Teams.

**What solution would be ideal for you?**
Allowing the Ui library to receive voip type push notification and raise a CallKit incoming call request, and hang up to terminate the Callkit session.

**What alternatives have you considered?**
N/A

**Is there any additional information for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by iaulakh** [comment]
Hello everyone!!

We're more than happy to announce our newest update to the UI Library for native platforms – introducing the feature of one-on-one calls for Android and iOS! With this latest release, initiating a call is as simple as a tap, and recipients will be promptly alerted with a push notification to answer or decline the call.
For iOS, we've seamlessly integrated[ CallKit for a native iOS](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fcommunication-services%2Fhow-tos%2Fui-library-sdk%2Fcallkit&data=05%7C02%7Ciaulakh%40microsoft.com%7Ca3f54612cf114ce8167408dc106e7202%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638403313809315850%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PElFQRGjHObYD1oqxKV%2Betp9jHaslUoCEqX1lG7G1i8%3D&reserved=0) call experience. This means your calls will feel right at home on any iOS device, blending perfectly with the user's expectations and device behavior.

Our UI library has been meticulously designed to encapsulate an end-to-end experience that requires no complex coding. Immerse your users in a calling experience that's built on the best UI/UX practices, without the need to spend precious time developing the UI layer – we've got you covered.

This feature is currently in public preview, and we encourage you to dive into the documentation [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fazure%2Fcommunication-services%2Fhow-tos%2Fui-library-sdk%2Fone-to-one-calling%3Ftabs%3Dkotlin%26pivots%3Dplatform-android&data=05%7C02%7Ciaulakh%40microsoft.com%7Ca3f54612cf114ce8167408dc106e7202%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638403313809326169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nIp1uTLPUZJ1CunEbmzMKugefvH9wfBnfRClqziNHSw%3D&reserved=0) to get started. Experience the ease of integrating high-quality calls into your application today!

Warm Regards!

UI Library team
