### ISSUE TITLE
Use resource_bundles instead of resources in podspec

### ISSUE THREAD

**Issue by JasonWeinzierl** [Azure/communication-ui-library-ios#676]
**What feature are you requesting?**

Use `resource_bundles` [per CocoaPods' recommendation](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles) instead of `resources`.

**What would be the benefit of adding this feature?**

Better compatibility. Name collisions can occur when using this library, requiring the dev to manually remove the `Assets.car` file from the project's output paths.

**What solution would be ideal for you?**

A podspec of these libraries are published with `resource_bundles` instead of `resources.

**What alternatives have you considered?**

Writing a script to fix build failures.

**Comment by ahammer** [comment]
Hi Jason, would you be free to tell us more details about the issue so that we can investigate the issue further and reproduce locally?

- What conflicts are you experiencing?
- Can you include the script you used to fix build failures?
- How to reproduce on a clean project?

This will allow us to further understand the issue and work towards a resolution.

**Comment by JasonWeinzierl** [comment]
This GitHub issue for MessageKit has a detailed explanation of the general problem: https://github.com/MessageKit/MessageKit/issues/1573

Right now, it's hard to reproduce this issue fully because it occurs when using pod static framework, and there's another bug with pod static framework in the headless SDK: https://github.com/Azure/azure-sdk-for-ios/issues/1539

But once that issue is resolve and static framework is supported, then users of the UI library will begin to see problems described in that MessageKit issue.

**Comment by JasonWeinzierl** [comment]
Calling SDK

**Comment by ahammer** [comment]
After a detailed discussion within our team, I regret to inform you that we do not have plans to support resource-bundles in our iOS library/framework at this time. This feature primarily impacts static frameworks, and as such, we currently have no plans to support static frameworks in the future. This decision is based on our long-term strategic direction and the need to prioritize resources to deliver the most value to our users.

As a result, we will be closing this issue. If you have any further questions or concerns, please do not hesitate to reach out to us.

**Comment by RajRohitYadav** [comment]
Hey, we are facing a build issue related to Assets.car and we suspect that it's potentially beccause of resources in podspec. Have added further details here https://github.com/Azure/communication-ui-library-ios/issues/1034
