### ISSUE TITLE
Azure Calling, CallingUI, ChatUI - Support SwiftPM

### ISSUE THREAD

**Issue by gezamiklo** [Azure/communication-ui-library-ios#683]
**What feature are you requesting?**

Calling SDK cannot be integrated in the project using Swift Package Manager. The UI libraries still do not support SwiftPM.

**What would be the benefit of adding this feature?**

Part of the Azure ecosystem supports SwiftPM. The rest should be loaded by cocoapods or manually. Using Cocoapods introduces new problems in existing projects which use SwiftPM. When integrating manually the developer has to access a viable combination of package versions.

Provided you support SwiftPM for those means the developer can intergrate the whole communication service with a single package manager, without the hassle of manual integration.

**What solution would be ideal for you?**

Add SwiftPM support in:
- AzureCommunicationCalling
- AzureCommunicationCallingUI
- AzureCommunicationChatUI

**What alternatives have you considered?**

Integrating the above SDKs manually.

**Is there any additional information for your request?**

Manually integrating AzureCommunicationCalling causes build time failure because the lib is compiled with an older swift version. (Setting "Build Libraries for Distribution" to YES could solve this). But this should be another issue.

**Attach screenshots or images add detail to your request:**
![List of packages loaded by SwiftPM - all versions are fixed](https://github.com/Azure/communication-ui-library-ios/assets/221177/e265ebd3-2fb7-4ad6-aea0-0dd08dea721d)
![The Chat UI can be integrated manually](https://github.com/Azure/communication-ui-library-ios/assets/221177/5453e6ff-7169-4e05-873f-f50fd2a93a6e)

**Comment by ahammer** [comment]
Thank you for your feature request regarding Swift Package Manager (SwiftPM) support for our AzureCommunication SDKs.

SwiftPM support is something we are exploring internally. We recommend continuing to use Cocoapods or manual integration methods for the time being.

We've noted your feedback about the "Build Libraries for Distribution" setting, and will explore its viability in future SDK versions.

Your suggestions are important to us and will be factored into our ongoing development considerations.

Sincerely, 
  Adam Hammer
