### ISSUE TITLE
AzureCommunicationUICalling 1.2.0 - Initializer for conditional binding must have Optional type, not 'String'

### ISSUE THREAD

**Issue by willieburger34** [Azure/communication-ui-library-ios#684]
Using XCode 15 on a CapacitorJS project

I am unable to build with the UI Calling Library included.

I receive a compile error: -  Initializer for conditional binding must have Optional type, not 'String'
in AzureCommunicationUICalling -> IconWithLabelButton

ios/App/Pods/AzureCommunicationUICalling/AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Button/IconWithLabelButton.swift:34:20 Initializer for conditional binding must have Optional type, not 'String'

my POD file:

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'ByteowlsCapacitorOauth2', :path => '../../node_modules/@byteowls/capacitor-oauth2'
  pod 'CapacitorCommunityAppcenterCrashes', :path => '../../node_modules/@capacitor-community/appcenter-crashes'
  pod 'CapacitorCommunityFirebaseAnalytics', :path => '../../node_modules/@capacitor-community/firebase-analytics'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapacitorSecureStoragePlugin', :path => '../../node_modules/capacitor-secure-storage-plugin'
  pod 'TerraCapacitor', :path => '../../node_modules/terra-capacitor'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  use_frameworks!
  

  capacitor_pods

  # Add your Pods here
  pod 'OpenCV', '~> 4.3.0'
  pod 'Starscream', '~> 4.0.0'
  pod 'AzureCommunicationUICalling', '1.2.0'
 
end

post_install do |installer|
  assertDeploymentTarget(installer) 

  installer.pods_project.targets.each do |target|   
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['IOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION']='YES'
      
    end
  end

end

**Comment by ahammer** [comment]
Thank you for bringing this to our attention.

After carefully reviewing the provided code, we confirm that `buttonLabel` from the `viewModel` is correctly defined as an `Optional` and the `if let` syntax used for unwrapping this `optional `appears to be correct. Therefore, the specific error you're encountering does not seem to originate from this particular block of code.

As of now, we haven't extensively tested our library with Capacitor.js. This might introduce some unforeseen issues, and your case could potentially be one of them.

We encourage you to double-check your environment setup and project configuration to rule out any issues there. 

To request support of Capacitor.js, you can follow up here
[Azure Communication Services - Share your idea](https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858)
