### ISSUE TITLE
Add compatibility for AzureCommunicationCalling 2.4.1 

### ISSUE THREAD

**Issue by InquestApp-Admin** [Azure/communication-ui-library-ios#690]
**What feature are you requesting?**
We would like to be able to use ACS Calling CallKit and this library together. ACS Calling SDK CallKit requires AzureCommunicationCalling 2.4.1.  This library is currently not compatible with AzureCommunicationCalling 2.4.1 cocoapod.
[https://learn.microsoft.com/en-us/azure/communication-services/how-tos/calling-sdk/callkit-integration]

**What would be the benefit of adding this feature?**
We would be able to use the CallKit features of ACS Calling SDK in our app along with the UI library.

**What solution would be ideal for you?**
Works with AzureCommunicationCalling 2.4.1

**What alternatives have you considered?**

**Is there any additional information for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by iaulakh** [comment]
Hi @InquestApp-Admin,

Thank you for raising a feature request. The request to add CallKit support for the UI library is currently in the backlog. We will provide more information once we begin working on the integration.

In the meantime, please take a look at the [Calling] Enable support for CallKit pull request, available at [link](https://github.com/Azure/communication-ui-library-ios/pull/680). If this is helpful for you, you can also fork and integrate it into your project.

Thank you.

**Comment by iaulakh** [comment]
Hi @InquestApp-Admin ,

Please find CallKit [QuickStart](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/ui-library-sdk/callkit). The 1.8.0 version of UI Library supports CallKit.
