### ISSUE TITLE
Add “Docked” mode

### ISSUE THREAD

**Issue by etown** [Azure/communication-ui-library-ios#694]
What feature are you requesting?
The call composite always presents modally. This is very limiting because often users want to continue to interact with the application while on a call.

What would be the benefit of adding this feature?
Improved user experience, since users wouldn't be in a modal and could interact with the application.

What solution would be ideal for you?
A minimized button which would transition the composite to a minimized mode which could be a draggable window, or docked view.

**Comment by pavelprystinka** [comment]
@etown 

Thank you for raising a feature request. We are currently working on allowing user to multitask in the App while on the call by providing a Picture-in-Picture support to display call participant and hiding rest of the Calling UI.

There is no particular date we could share when this feature will be released, but you can see feature branch [here](https://github.com/Azure/communication-ui-library-ios/tree/feature/system_pip).

Thank you.
