### ISSUE TITLE
Xcode 16 crash on application run: Symbol not found

### ISSUE THREAD

**Issue by billp** [Azure/communication-ui-library-ios#964]
**Describe the bug**
The app crashes at runtime with a symbol not found error related to Swift protocol conformance when running with Xcode 16 and iOS 18. This issue did not occur in Xcode 15.4.

**To Reproduce**
1. Run the app using Xcode 16.
2. Use iPhone 16 Pro simulator, iOS 18.

**Expected behavior**
The application should run without crashing, as it did in Xcode 15.4.

**Screenshots**
N/A

**AzureCommunicationUILibrary (please complete the following information):**
- Version: 1.10.0

**Smartphone (please complete the following information):**
- Device: iPhone 16 Pro
- OS: iOS 18

**Additional context**
```
The following runtime error is observed:
dyld[25324]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: <04AD06A6-6F99-3D10-B524-DF08994AC37F> /Users/xzy/Library/Developer/CoreSimulator/Devices/8DF90DA5-8D8C-4FAC-8112-3F8C41D3B1BA/data/Containers/Bundle/Application/83082E86-D001-4D60-988C-619EE8C480C3/MyApp.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling
  Expected in:     <EB41C9A9-455C-3B7A-8C14-77C27272CBCE> /Users/xzy/Library/Developer/CoreSimulator/Devices/8DF90DA5-8D8C-4FAC-8112-3F8C41D3B1BA/data/Containers/Bundle/Application/83082E86-D001-4D60-988C-619EE8C480C3/MyApp.app/Frameworks/AzureCommunicationCommon.framework/AzureCommunicationCommon
```

**Comment by pavelprystinka** [comment]
Thank you @billp for pointing this out.
We are working on this now and will be back with a solution soon.

**Comment by pavelprystinka** [comment]
He @billp,

Please update to a new version 1.11.0. That should resolve the issue.
