### ISSUE TITLE
Camera Multitasking Inconsistently Active in Background During Video Calls

### ISSUE THREAD

**Issue by billp** [Azure/communication-ui-library-ios#980]
**Describe the bug**  
The camera multitasking feature is not working as expected. Despite setting the correct entitlements and configurations, the camera only stays active in the background occasionally, when it should remain on every time the app is moved to the background.

**To Reproduce**  
1. Start a video call using the library.
2. Ensure the camera is on.
3. Move the app to the background.
4. Observe that the camera doesn't remain active in the background.

Strange thing is that if you move the app to the background and then back to the foreground multiple times you will observe that the camera will remain active in the background occasionally.

**Expected behavior**  
The camera should stay on and active in the background every time the app is moved to the background during an ongoing video call.

**AzureCommunicationUILibrary (please complete the following information):**  
- Version: 1.11

**Smartphone (please complete the following information):**  
- Device: iPhone 13 Pro  
- OS: iOS 18.0

**Additional context**  
The camera multitasking isn't functioning properly. I've added the entitlement `com.apple.developer.avfoundation.multitasking-camera-access` and received approval from Apple. Additionally, I set `enableMultitasking: true` and `enableSystemPictureInPictureWhenMultitasking: true` in `CallCompositeOptions`. The provisioning profiles have been updated to include this entitlement. However, after moving the app to the background and foreground multiple times while the camera is on, it stays active in the background only once, but it should remain on every time the app is in the background.

**Comment by ahammer** [comment]
Thanks for bringing this issue to our attention. We will start investigations and get back to you as soon as possible.

**Comment by ahammer** [comment]
There is some fixes in our dependency libraries that will be rolling out to help with this.
This is in progress and expected to be in included in release 1.13.0 of the UI Library.

There isn't an exact date for the release yet, but I'd guess some time in November.

I'll leave this ticket open until resolved.

**Comment by pavelprystinka** [comment]
Hi @billp 
We have accelerated the release of the feature for displaying incoming video in Picture-in-Picture mode when the app is in the background. This functionality is now available starting from version 1.12.0, as the necessary fixes were implemented earlier than anticipated.
 
Please note that the local user’s selfie Picture-in-Picture will only be available when the app is in the foreground, as iOS does not support this feature while the app is in the background.
