### ISSUE TITLE
Error connecting to call using XCode 16

### ISSUE THREAD

**Issue by logikonline** [Azure/communication-ui-library-ios#983]
**Describe the bug**
I need help getting this library to connect.  I started using the .NET Maui version, as that is my desired method, but seeing a few errors - I tried the Xcode version here to see if I could resolve them.  It will not connect to Teams or 1-N for the call to join.  Android is working, as seen in my attached video.

I resolved the requirement for the orientation method, which changed as of iOS 16, and was seeing errors, which I thought was the crux of the join issue, but there is more to it.

**To Reproduce**
Use the latest code and follow the instructions for the demo app.
Try to join either a Teams or 1-N call.  I didn't try the Group or Room since I used the sample.

**Expected behavior**
To join a call

**Screenshots**
https://share.zight.com/bLuvbewm -- video showing the platforms

**AzureCommunicationUILibrary (please complete the following information):**
 - Version 1.11.0
 - Xcode: 16

**Smartphone (please complete the following information):**
 - Device: Simulator 16 and 16 Pro
 - OS: 18.0

**Additional context**
Here is my change for the Orientation issue, which is throwing the error.  This did fix it since it appears iOS made a change requiring this approach.  [ Orientation Fix ](https://github.com/Azure/communication-ui-library-ios/commit/961d640627331e1e54b3138e19d8d6bcd2b09148)

Any help is greatly appreciated. I want to migrate from Twillio to my Azure cloud, but I need iOS to work in Maui like Android.  I really appreciate any help you can provide.

**Comment by pavelprystinka** [comment]
Hi @logikonline,

Thanks for reaching this out. I see you are using a DemoApp in this repository and running iOS App on the simulator. By default DemoApp enables integration of CallComposite with CallKit. Simulator does not support CallKit integration and will be crushing. You can either disable CallKit (tap settings button) or run App on the real device.

Hope that helps.

**Comment by logikonline** [comment]
Thank you so much for the reply. Question. I fixed the error with the Orientation that is bubbling up to Maui. Should that be made into a PR?

**Comment by pavelprystinka** [comment]
If you could submit a PR that would be awesome!
