### ISSUE TITLE
["1.5.0"]  App crashing in iOS 18 with Xcode 16.1

### ISSUE THREAD

**Issue by smartfuturesg** [Azure/communication-ui-library-ios#997]
**App crashing in iOS 18 with Xcode 16.1**
Recently I have updated my Mac Os with 15.1 (24B83) Sequoia. Also, updated Xcode with 16.1
After updating this, when I tried to run app, app compiled successfully and installed on my phone. But on launch app got crashed. Attaching app crashing reason below.

dyld[88013]: Symbol not found: (__ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E)
  Referenced from: '/private/var/containers/Bundle/Application/3CEE001F-9EA6-438A-BFE3-C0EDAA02BA8E/ISOSRPM.app/Frameworks/AzureCommunicationCalling.framework/AzureCommunicationCalling'
  Expected in: '/private/var/containers/Bundle/Application/3CEE001F-9EA6-438A-BFE3-C0EDAA02BA8E/ISOSRPM.app/Frameworks/AzureCommunicationCommon.framework/AzureCommunicationCommon'
![Image](https://github.com/user-attachments/assets/67fc16e1-4f65-45a8-b89a-bea9583fd694)

Also, If possible please resolve this as well as there is no iOS 12 support in this new Xcode. Everytime, need to update manually through code.

 ![Image](https://github.com/user-attachments/assets/3fb22c16-17fa-42d9-97b3-6c9727dc4038)

**AzureCommunicationUILibrary (please complete the following information):**
 - Version 1.5.0

**Smartphone (please complete the following information):**
 - Device: iPhone 12, iPad
 - OS: iOS 18

**Comment by jamchengms** [comment]
Hi @smartfuturesg, we recognize that you are on a GA build that's dated back in Dec 2023. Please update the AzureCommunicationUICalling to version 1.12.0 to resolve the issue you are facing.
